language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend

# Tagging
  - docker tag reverseproxy atefdev2/reverseproxy:v1
  - docker tag udagram-api-feed atefdev2/udagram-api-feed:v1
  - docker tag udagram-api-user atefdev2/udagram-api-user:v1
  - docker tag udagram-frontend atefdev2/udagram-frontend:local



# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push atefdev2/reverseproxy:v1
  - docker push atefdev2/udagram-api-feed:v1
  - docker push atefdev2/udagram-api-user:v1
  - docker push atefdev2/udagram-frontend:local
  
