apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-secret

data:
  credentials: |
    [default]
    aws_access_key_id=AKIA2MZHEA3GUGLZJX45
    aws_secret_access_key=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