apiVersion: apps/v1

kind: Deployment

metadata:

  name: backend-user

  labels:

    app: backend-user

spec:

  replicas: 2

  selector:

    matchLabels:

      app: backend-user

  template:

    metadata:

      labels:

        app: backend-user

    spec:

      containers:

      - name: backend-user

        image: atefdev2/udagram-api-user:v1

        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
        envFrom: 
        - configMapRef:
            name: udagram-env
        - secretRef:
            name: postgres
